### ISSUE TITLE
support getInitialProps, similar to next.js

### ISSUE THREAD

**Issue by sessionboy** [lucasecdb/casterly#361]
Sample code:
```js
// src/IndexPage.jsx

export default ({ user }) => {
  return (
    <>
      <p>Hello world!</p>
      <div>{ user?.name }</div>
    </>
  )
}

export const getInitialProps = async () =>{
  const user = await fetch(url).then(res=>res.json());
  return {
    user
  }
}
```
```js
// routes.js

export default [
  {
    component: () => import('./IndexPage'),
    path: '/',
  },
]
```

The getInitialProps function is executed when the server is rendering and switching routes.

Hope that the library can be used in production as soon as possible.

**Comment by lucasecdb** [comment]
hey @sessionboy! thanks for the issue, do you want to try and open a PR for this one? I don't think I'll have the time right now

**Comment by sessionboy** [comment]
It's ok, but i'm as busy as you, I am now busy developing the backend of my project. In the future, when I have free time, I will try to submit a PR.

**Comment by lucasecdb** [comment]
with the upcoming announcement and release of React 18, you'd be able to do this by using data-fetching strategies the React team is working on (such as using either Suspense or server components) without any changes on Casterly. So I'll close this issue because that will be the recommended way to do data fetching on SSR, ok?
